# Generated by Django 2.0.1 on 2021-06-28 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('exam_type', models.CharField(max_length=100)),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grade.Grade')),
            ],
        ),
    ]
