# Generated by Django 2.0.1 on 2021-06-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
    ]
