# Generated by Django 2.0.1 on 2021-07-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210630_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='grade.Grade'),
        ),
    ]
