# Generated by Django 3.2.4 on 2021-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210610_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teaching'), (2, 'Non-Teaching')], default=1, null=True),
        ),
    ]
