# Generated by Django 2.0.1 on 2021-07-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210712_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='account.ParentProfile'),
            preserve_default=False,
        ),
    ]
