# Generated by Django 2.0.1 on 2021-07-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210712_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponserprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teaching'), (2, 'Non-Teaching')], default=1, null=True),
        ),
    ]
