# Generated by Django 2.0.1 on 2021-07-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210719_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='school.School'),
        ),
        migrations.AlterField(
            model_name='sponserprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponser', to='school.School'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='school.School'),
        ),
    ]
