# Generated by Django 2.0.1 on 2021-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='category',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='year',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total_payed_amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_detail',
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ManyToManyField(related_name='detail', to='payment.Category'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
