# Generated by Django 2.0.1 on 2021-07-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210615_0605'),
        ('payment', '0003_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_category', to='school.School'),
            preserve_default=False,
        ),
    ]
