# Generated by Django 2.0.1 on 2021-07-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_auto_20210707_0440'),
        ('payment', '0004_category_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='grade.Grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='school.School'),
        ),
    ]
