# Generated by Django 2.0.1 on 2021-07-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='unique_id',
        ),
    ]
